### ISSUE TITLE
Sword of Nuln

### ISSUE THREAD

**Issue by codex-krcg** [lionel-panhaleux/krcg#100]
- **text:** Sword of Nuln and aggravated damage: If the Sword does aggravated damage for whatever reason, the vampire pays the normal amount of blood to prevent destruction. Aggravated damage cannot be healed by definition.  Sword of Nuln and Taste of Vitae: The Taste will count the amount of blood burnt healing the damage.  Sword of Nuln and Regenerative Blood: The vampire with Regenerative Blood heals two damage from the Sword for each two (double the normal amount of one) blood he spends. So if the Sword does 1 damage, the vampire burns 2 blood to heal it. If it does 2, he burns 2 blood to heal it (that's twice the amount he would normally burn). For 3 or 4 damage, he burns 4 blood. And so on.
- **link:** http://www.vekn.net/index.php/card-lists/116-anarchs-faq-clarifications-and-rulings

**Comment by lionel-panhaleux** [comment]
Found original LSJ ruling instead, as to not add yet another source of rulings.
