### ISSUE TITLE
Sword of Nuln

### ISSUE THREAD

**Issue by codex-krcg** [lionel-panhaleux/krcg#101]
- **text:** IANLSJ but AFAIK "You must burn any/all blood to prevent as much damage as possible". Therefore, needs to burn 2 blood to heal 1 damage dealt. Burns 1 blood, fails to heal the damage and goes to torpor.
- **link:** http://www.vekn.net/forum/rules-questions/78659-clarification-needed-sword-of-nuln-and-heal-damage#99960

**Comment by lionel-panhaleux** [comment]
Will link original LSJ ruling.
