### ISSUE TITLE
Blissful Agony

### ISSUE THREAD

**Issue by codex-krcg** [lionel-panhaleux/krcg#131]
- **text:** Remove TOM 19960225, add "VAL: dodge prevents new combat"
- **link:** https://groups.google.com/g/rec.games.trading-cards.jyhad/c/jqPoW66sEkY/m/RH3yS-8MQCoJ

**Comment by lionel-panhaleux** [comment]
I think TOM ruling still applies to the animalism level. Of course, let's add the dodge thing.
