### ISSUE TITLE
Blissful Agony

### ISSUE THREAD

**Issue by codex-krcg** [lionel-panhaleux/krcg#132]
- **text:** VAL: in the new combat, if no-one is acting, the target of the action goes first 
- **link:** https://groups.google.com/g/rec.games.trading-cards.jyhad/c/jQkkiC3I8P8/m/uDZ--HnPtf0J

**Comment by lionel-panhaleux** [comment]
Already listed, although the wording is a bit more direct: "In the new combat, the opponent goes first."
