### ISSUE TITLE
Nephandus vs. Sticks

### ISSUE THREAD

**Issue by warwar1980** [lionel-panhaleux/krcg#16]
we have problem in past about Nephandus vs. Sticks,how much counters from stick need to burn due to nephandus text,so if you anounce stick 2 damage,but nephandus text reduce damage,how much counters stick burn-answer is 1,here is rule:  http://www.vekn.net/forum/rules-questions/75865-nephandus-vs-sticks#82119

**Comment by lionel-panhaleux** [comment]
Thanks ! I'll add this one quickly.

**Comment by lionel-panhaleux** [comment]
Link above allows you to see the corresponding change --^
It will be available in the Codex on the next release (later today or tomorrow I think)
