### ISSUE TITLE
Faceless Night

### ISSUE THREAD

**Issue by codex-krcg** [lionel-panhaleux/krcg#168]
- **text:** please read all,we need this about,FN vs deflections,FN vs referendum,and vs every other action,combat for example. by james if you fail block,you can play deflection,and if bleed back to you,you still unlocked and can react again. pls read all,we need this part in codex,if something not clear we need to continue to ask on this topic until ankha resolve all doubt. 
- **link:** https://www.vekn.net/forum/rules-questions/63821-faceless-night-x-deflection?starhttps://www.vekn.net/forum/rules-questions/63821-faceless-night-x-deflection?start=0t=0

**Comment by lionel-panhaleux** [comment]
Sure. This is pretty clear to me. Faceless effect only kicks in "before action resolution", rulings state this means at resolution, before resolving the effect, so after deflection or any other reaction that is played before resolution. I think ruling #3 covers that, I'll try to reword it better, add the Deflection example to it and a link to the thread. Thank you for the input !

> 3. The lock of the minion happens at action resolution. He still locks if he unlocked before that (eg. with Guard Dogs). Only cards that can be played "after action resolution" can be played after the lock. [ANK 20171017]

**Comment by lionel-panhaleux** [comment]
So, I reworded to include the point about Deflection. I cannot include the link you provided as there is no answer from the current RD at the time (That would be Pascal) in there.
