### ISSUE TITLE
Cards sharing a ruling

### ISSUE THREAD

**Issue by GiottoVerducci** [lionel-panhaleux/krcg#18]
Some cards share a ruling, for instance:

"7","Abactor is an action in its own right. Kyoko would not steal blood from a vampire by playing Abactor.","https://groups.google.com/d/msg/rec.games.trading-cards.jyhad/-hy9E1u2t_o/CPU8rltzhesJ","2009-06-06","LSJ"

Should be associated to Abactor and Kyoko.

But it requires moving each ruling to a different "table" and adding references instead of the ruling itself, making it more difficult to maintain.

**Comment by lionel-panhaleux** [comment]
I agree, for now rulings are just duplicated under the two cards.

I think many rulings are easier to read if you adapt their wording to the appropriate card. For your example, we could put the ruling under Kyoto only, or under both with slightly different wordings, like:

Kyoko:
    - "Cannot chose to steal blood from a vampire when using another hunt action (eg. {Abactor})."

Abactor:
   - "The blood comes from the blood bank even if the vampire has an alternate hunt action with another source for the blood (eg. {Kyoko})"

On the other hand, many rulings are duplicated with the exact same wording on multiple cards. The most striking examples are the "general rulings" of the VEKN website. Still, even in this case adaptations can be made card by card, which is useful for readability.

For now, I'm leaning on the side of keeping the cards as keys. It's a close call though. Anyone let me know if you feel strongly we should change that or if you have other arguments.

**Comment by GiottoVerducci** [comment]
Is {whatever} the syntax for a link towards the card named "whatever"?

**Comment by GiottoVerducci** [comment]
Many two files are required:
The existing file
Another "general ruling files" that could be linked to cards.
For instance:

```
Action Continues As If Unblocked:
    - If an effect continues a blocked action "as if unblocked", then all action modifiers and reaction cards, including stealth and Dawn Operation or Wake with Evening's Freshness, are still in effect. [RTR 19941109] => 100771:Form of Mist / 101222:Mirror Image 
```

**Comment by lionel-panhaleux** [comment]
I like this idea ! I think this would settle the issue nicely.
I'll work on a PR proposal.
