### ISSUE TITLE
Search algorithm

### ISSUE THREAD

**Issue by GiottoVerducci** [lionel-panhaleux/krcg#19]
The search algorithm should give more weight to exact matches, especially when starting with the search pattern.

For instance, "the ru" returns

Abandoning the Flesh
Absolution of the Diabolist
Absorb the Mind...

It should return as first choice "The Rumor Mill" then more distant answers.

"Pentex" returns
Enzo Giovanni, Pentex Board of Directors
Enzo Giovanni, Pentex Board of Directors (ADV)
Harold Zettler, Pentex Director
Pentex(TM) Loves You!
Pentex(TM) Subversion

The 2 last entries should be first. We could even refine more using the occurence hits from the TWDA to see that Pentex(TM) Subversion is more likely than Pentex(TM) Loves You!, but that's a further improvement.

**Comment by lionel-panhaleux** [comment]
Good point, it bothered me too.
I'll see to it. If anyone wants to submit a PR, you're welcome.
