### ISSUE TITLE
Crypt's Sons

### ISSUE THREAD

**Issue by codex-krcg** [lionel-panhaleux/krcg#192]
- **text:** The initial blocking minion is locked even if the action continues. (I am not sure if that is the good way to submit anything here so feel free to let me know : remi.cavaille@gmail.com) Regards, Rémi.)
- **link:** https://www.vekn.net/forum/rules-questions/79008-crypt-s-sons-lock-and-obedience#101525

**Comment by lionel-panhaleux** [comment]
It's the right way to submit Remi ☺︎ Thanks for the feedback !

**Comment by lionel-panhaleux** [comment]
Fixed @ b27b61dfc72f6ea1f96943575abb658b8247f7c8
