### ISSUE TITLE
Carolina Vález

### ISSUE THREAD

**Issue by codex-krcg** [lionel-panhaleux/krcg#194]
- **text:** She is immune to unlock damage from Abyssal Hunter and Wendell Deburton
- **link:** https://www.vekn.net/forum/rules-questions/56821-carolina-valez-immunity#56822

**Comment by lionel-panhaleux** [comment]
Ankha was not RD at the time this answer was posted - an official link would be required to add the ruling.

**Comment by GiottoVerducci** [comment]
https://www.vekn.net/forum/rules-questions/56821-re-carolina-valez-immunity?start=6#101741

**Comment by lionel-panhaleux** [comment]
Thank you!
