### ISSUE TITLE
seating.py: computation of "relative position" rule

### ISSUE THREAD

**Issue by emimeswift** [lionel-panhaleux/krcg#207]
In the `fast_total` function to quickly compute the energy of the configuration, the value of rule 6 (position) is computed using:

`len(numpy.argwhere(measure.opponents[:, :, 1:6] > 1)) // 2`

However, column 6 is not one of the standard relative positions (prey, predator, etc.): it indicates if players are "neighbors". Shouldn't the interval be `1:5` instead?

**Comment by lionel-panhaleux** [comment]
Well `1:6` means "1 to 6 excluded", so columns 1, 2, 3, 4, 5. Usually intervals in C-derived languages are always open on the right (ie. `1:6` means `[1, 6(`, as does `range(1, 6)`). Am I missing something?

**Comment by emimeswift** [comment]
I am very sorry for wasting your time with my ignorance of Python :-(
