### ISSUE TITLE
Darkling Trickery

### ISSUE THREAD

**Issue by codex-krcg** [lionel-panhaleux/krcg#218]
- **text:** I think this RTR is outdated considering it forbid to play a strike after a S:CE is played by an acting minion
- **link:** https://groups.google.com/d/msg/rec.games.deckmaster/_6CXoKTSLnw/FdG67-3HEAQJ

**Comment by lionel-panhaleux** [comment]
AFAICT the ruling still applies: no damage against a S:CE. Same as Carrion Crows. Would need a more recent ruling stating otherwise to change it. Or am I missing something?
