### ISSUE TITLE
Weighted Walking Stick

### ISSUE THREAD

**Issue by codex-krcg** [lionel-panhaleux/krcg#219]
- **text:** Burn no token if no damage is inflicted (eg. Blood Fury)
- **link:** https://groups.google.com/g/rec.games.trading-cards.jyhad/c/pFBC8AX1g60/m/QTKr_aQBTbEJ

**Comment by kschaefe** [comment]
```
Burns no tokens if no damage is inflicted (e.g. Blood Fury)
```

`Burns` is smoother English than `burn`.
