### ISSUE TITLE
Grey Thorne

### ISSUE THREAD

**Issue by codex-krcg** [lionel-panhaleux/krcg#227]
- **text:** He can't play cards requiring both cel and pot
- **link:** https://groups.google.com/g/rec.games.trading-cards.jyhad/c/vZ13bh7FEvQ/m/KaZlbqc4LO0J

**Comment by lionel-panhaleux** [comment]
Ruling is related to Infernal Familiar, and does not state it does not provide two disciplines. A better ruling is required.
