### ISSUE TITLE
Not enough blood for Minion Tap / Villein

### ISSUE THREAD

**Issue by lionel-panhaleux** [lionel-panhaleux/krcg#25]
If Minion Tap or Villein are announced to a certain amount, and the target has less at the time of resolution, you take what's left.

Didn't manage to find a ruling on this. If anyone gets his hand on a link, please give it here ☺︎

**Comment by GiottoVerducci** [comment]
https://groups.google.com/d/msg/rec.games.trading-cards.jyhad/nrXTh1XKJJ8/KF7iiXQk3jsJ
