### ISSUE TITLE
Aabbt Kindred

### ISSUE THREAD

**Issue by codex-krcg** [lionel-panhaleux/krcg#257]
- **text:** Cannot be played by vampires who aren't controlled.
- **link:** https://groups.google.com/d/msg/rec.games.trading-cards.jyhad/80KRDjVFkyg/TBJso9Ra_9QJ

**Comment by lionel-panhaleux** [comment]
I don't see anything about Aabbt Kindred in the ruling - nor do I understand the text here - it seems to have nothing to do with Aabbt Kindred.
