### ISSUE TITLE
Unseen Hibernation

### ISSUE THREAD

**Issue by codex-krcg** [lionel-panhaleux/krcg#303]
- **text:** If an "action ends (uncusessfully)" this is ruled as äquivalent to "the action fails" therefore Ruling #1 does not apply here, the source actually states, if an action fails, modifiers whose conditions are satiesfoed, can still be played.
- **link:** https://www.vekn.net/forum/rules-questions/79389-when-does-nra-apply-not-apply?start=6#103563

**Comment by lionel-panhaleux** [comment]
The ruling has to do with NRA, not with the ability of playing further modifiers or not. AFAIK the ruling on ended actions still stands. Feel free to ask a confirmation/infirmation on the forum.

**Comment by lionel-panhaleux** [comment]
My bad (cf. ANK 20221205 & ANK 20220118). Fixed now
