### ISSUE TITLE
Razor Bat

### ISSUE THREAD

**Issue by codex-krcg** [lionel-panhaleux/krcg#314]
- **text:** First ruling is incorrectly interpreted and needs rephrasing, damage from a retainer is considered environmental
- **link:** http://www.vekn.net/forum/rules-questions/76717-retainers-damage-and-disciplines#88129

**Comment by lionel-panhaleux** [comment]
Would have helped if the correct ruling had been attached: https://www.vekn.net/forum/rules-questions/76687-retainers-inflicting-damage-environmental?start=6#104017
