### ISSUE TITLE
Escaped Mental Patient

### ISSUE THREAD

**Issue by warwar1980** [lionel-panhaleux/krcg#33]
him need to declare HS aggr,cant say HS,and later declare as is aggr http://www.vekn.net/forum/rules-questions/77798-announcing-strikes-and-intention?start=0

**Comment by lionel-panhaleux** [comment]
This is more a discussion about how to judge / handle the situation in tournament.
Nobody seems to misunderstand that the patient can do both a normal strike or the special strike provided by the card text.

I can still add this If you find the card wording lacks precision and want it to be included.

**Comment by warwar1980** [comment]
If you see in link what i sent to you these people dont know to him need to anounce in strike window is want to use HS aggr,is not work as example some protean cards where you can play after oposing declare strike,and ankha there explain how mental strike works. to be honestly before ankha answer i also think diferent

**Comment by lionel-panhaleux** [comment]
OK I'll include it then
