### ISSUE TITLE
Precognition

### ISSUE THREAD

**Issue by codex-krcg** [lionel-panhaleux/krcg#336]
- **text:** The optional damage prevention does not carry over to another combat that isn´t the result of a block (e.g. Psyche! combat is not the result of a block)
- **link:** https://groups.google.com/g/rec.games.trading-cards.jyhad/c/8MR4bq0Cxj4/m/YgNsk8nGcREJ

**Comment by lionel-panhaleux** [comment]
Fixed @ 3b2c07cc3f5e5f2f26557e09ab11d6ab0e5316bc
