### ISSUE TITLE
disarm,taste,psyche,RR,TT

### ISSUE THREAD

**Issue by warwar1980** [lionel-panhaleux/krcg#35]
maybe is good to say how you can play these cards in any order: http://www.vekn.net/forum/rules-questions/76990-correct-order-impulse-for-combat-cards-after-combat?start=0

also specialy to say how if played TT RR or psyche,another cannot be played,ankha made mistake in this link and say how TT can be played after psyche,but him repair him answer in another link: http://www.vekn.net/forum/rules-questions/76990-correct-order-impulse-for-combat-cards-after-combat?start=0
here him repair this(so even him be confused,imagine how another players can be confused): http://www.vekn.net/forum/rules-questions/78241-relentless-reaper-vs-blissful-agony-and-scheduled-combat-rulings-ambiguity?start=0

**Comment by lionel-panhaleux** [comment]
About this one, I included it but it still seems awkward to me:
1. TT and RR can not be played after Psyche.
2. Disarm, Taste, etc. can be played before or after TT and RR.
3. Disarm, Taste, etc. can be played after Psyche.

Are we sure about this point 3 ? --^

**Comment by warwar1980** [comment]
in first link you can find: 
![image](https://user-images.githubusercontent.com/63711685/80855972-33a0d880-8c46-11ea-8606-e215c02f4778.png)

also is good to say how psyche cannot be played after RR or TT,because people make mistake about it,they think to can play it even for cicle

**Comment by warwar1980** [comment]
ankha confirm point 3 in vekn
