### ISSUE TITLE
ANK 20190425

### ISSUE THREAD

**Issue by GiottoVerducci** [lionel-panhaleux/krcg#365]
- ruling: 'Cards and effects that can be played "as the action is announced" can be played before it. [ANK 20190425]'

I don't understand what it is supposed to mean. "before it" is unclear (what does "it" refer to?)

Since the ruling seems to be associated to cards that are "only usable as the action is announced", it should probably say:

Must be played (as well as other "as the action is announced" action modifiers) before action modifiers that are not explicitly played "as the action is announced" (e.g., Conditioning)

**Comment by lionel-panhaleux** [comment]
Thanks for the improved wording!
