### ISSUE TITLE
High Aye

### ISSUE THREAD

**Issue by codex-krcg** [lionel-panhaleux/krcg#411]
- **text:** Played after action resolution in the same window as `Freak Drive`.
- **link:** https://groups.google.com/g/rec.games.trading-cards.jyhad/c/4e6z1_JWIzA/m/oMQz7oVR1O8J

**Comment by lionel-panhaleux** [comment]
The play can only happen on a block attempt (stealth card). It's the delayed discard effect that happens after resolution.
