### ISSUE TITLE
Soul Burn, Blood Fury, or Blood Rage

### ISSUE THREAD

**Issue by warwar1980** [lionel-panhaleux/krcg#42]
if oposing dodge-no efect these cards for add strike.
same if weapon use as first strike https://groups.google.com/forum/#!msg/rec.games.trading-cards.jyhad/GBcR6aNjIk4/DXPyqBM1R8kJ

same james copy here with add ankha answer where him say you can use ivory+rotscherk http://www.vekn.net/forum/rules-questions/75805-blood-fury-vs-ivory-bow-roetschreck#81952

i think if you add links best to add in all 3 cards,because if example problem happen during game and dont have link in soul burn page,maybe nobody remind how can find rule in blood fury page

**Comment by lionel-panhaleux** [comment]
Good one, I'll also include Personal Scourge 😉
