### ISSUE TITLE
Erciyes Fragments/pol act/Delaying Tactics

### ISSUE THREAD

**Issue by warwar1980** [lionel-panhaleux/krcg#43]
i find something,but im confused. so if you with EF take vote cards from you prey,and someone play DT,where goes this card? answer is here: https://groups.google.com/forum/#!searchin/rec.games.trading-cards.jyhad/Erciyes$20Fragments/rec.games.trading-cards.jyhad/vhSqnoAt_Bs/xMxOgeoCX7IJ

**Comment by lionel-panhaleux** [comment]
As explained in the thread, Delaying Tactics has since been reworded. It is clearer, but you're right I will add the ruling to Erciyes just to make it even more clearer.
