### ISSUE TITLE
Victim of Habit

### ISSUE THREAD

**Issue by codex-krcg** [lionel-panhaleux/krcg#475]
- **text:** victim of habit can be used to remove less than 3 copies of the card, however doing so does not make lose pool.
- **link:** https://groups.google.com/g/rec.games.trading-cards.jyhad/c/1TXRhYopt70/m/36CMhYD2Z8MJ

**Comment by lionel-panhaleux** [comment]
@GiottoVerducci registered it, even if I find this particular ruling a bit strange (I would have thought it impossible). If you want to take a look ☺︎
