### ISSUE TITLE
owain

### ISSUE THREAD

**Issue by warwar1980** [lionel-panhaleux/krcg#48]
well about owain,we always if ask to owain give blood use that first,but this player dont have impulse to give blood before we solve stuf https://groups.google.com/forum/#!msg/rec.games.trading-cards.jyhad/0u5KQWiutdg/lAZoy4vIwiIJ
that about impulse can be so complicated

**Comment by lionel-panhaleux** [comment]
Indeed, that's precise and complicated tournament-level stuff. Included !
