### ISSUE TITLE
Sniper Rifle

### ISSUE THREAD

**Issue by codex-krcg** [lionel-panhaleux/krcg#481]
- **text:** Ce ruling est bizarre :  - If a Slave locks to enter combat instead of a blocking minion, he cannot use the Rifle to set the range [ANK 20200115] On devrait avoir : - If a Slave locks to enter combat instead of an acting minion, the blocking minion cannot use the Rifle to set the range [ANK 20200115]
- **link:** https://www.vekn.net/forum/rules-questions/78321-slave-rule-and-acting-minion?start=6#98594

**Comment by lionel-panhaleux** [comment]
Wow, good catch!
