### ISSUE TITLE
Coma

### ISSUE THREAD

**Issue by codex-krcg** [lionel-panhaleux/krcg#527]
- **text:** Coma is a close range strike
- **link:** https://groups.google.com/g/rec.games.trading-cards.jyhad/c/e8-mp_OMsjw/m/8j8xS9GPK3MJ

**Comment by lionel-panhaleux** [comment]
TBF this is rulebook. Let's still add it as it is indeed a common question.
> Most strikes are effective only at close range, unless the strike is identified as ranged, does “R” damage, or is a defensive strike such as dodge or combat ends
