### ISSUE TITLE
Concordance

### ISSUE THREAD

**Issue by codex-krcg** [lionel-panhaleux/krcg#646]
- **text:** Aggravated damage done to a vampire with Concordance is still aggravated but handled as normal damage during damage resolution
- **link:** https://groups.google.com/g/rec.games.trading-cards.jyhad/c/0UGI9W2sSpk/m/An-ZYLIxAiwJ

**Comment by lionel-panhaleux** [comment]
This sounds just like the card text to me. "The damage is aggravated but it is handled as normal during damage resolution" is just a longer way to say "treats aggravated damage as normal damage", no? What is it that this additional ruling would clarify exactly? Maybe an example?
