### ISSUE TITLE
Jibade el-Bahrawi (G4)

### ISSUE THREAD

**Issue by codex-krcg** [lionel-panhaleux/krcg#657]
- **text:** When Jibade plays the Summoning at superior Presence, his card text gives the action an additional stealth.  The cost of the ally found is also reduced as it recruited from hand.
- **link:** https://groups.google.com/g/rec.games.trading-cards.jyhad/c/Eo9SQgj76K8/m/g1iOGx28IQQJ

**Comment by lionel-panhaleux** [comment]
Duplicate #635
