### ISSUE TITLE
Scourge of the Enochians

### ISSUE THREAD

**Issue by codex-krcg** [lionel-panhaleux/krcg#72]
- **text:** scourge,so when you use it,impulse pass,dont work as coven in dragonbound case,until now ankha dint confirm,so need to wait 
- **link:** http://www.vekn.net/forum/rules-questions/8235-re-coven-timing?start=30#99756

**Comment by warwar1980** [comment]
and sory for issue name,need to be scourge,i be on blood fury page when make issue,pls if you can somehow change issue name,because i beleive you have archive somewhere of issues and name topic can make confusion,but if no archive doesnt matter

**Comment by lionel-panhaleux** [comment]
Yes it's archived, there it's fixed 😉 I'd like to wait for an RD answer on this one. Maybe we will need to post a new topic on the forum.

**Comment by warwar1980** [comment]
idk whu is ankha still silent,hehe i made good question,yea we need to litle wait,if him no answer maybe go with new question

**Comment by lionel-panhaleux** [comment]
Yes sure. Let's wait a bit, I tried to explicit the possibilities as clearly as possible.
It's not Ankha's work to answer all our questions so we can't expect him to answer every day 😉 We're in no hurry.
