### ISSUE TITLE
Waste Management Operation

### ISSUE THREAD

**Issue by codex-krcg** [lionel-panhaleux/krcg#720]
- **text:** Crypt cards cannot be put into the library (or hand) and library cards can't be put into the library. Would be great if all cards that reference moving a non-type specific card from the ash heap to a non-public zone would have this ruling.
- **link:** https://groups.google.com/g/rec.games.trading-cards.jyhad/c/DY1OggZnMvs/m/7rSTvY34PRAJ

**Comment by GiottoVerducci** [comment]
"and library cards can't be put into the library" is wrong (should be "into the crypt")
