### ISSUE TITLE
Salvador Garcia (G4)

### ISSUE THREAD

**Issue by codex-krcg** [lionel-panhaleux/krcg#723]
- **text:** His abilities works on cards requireuing a baron. (ruling is missing from several cards like also garbibaldi, see crimethinc for current workding and other links)
- **link:** https://groups.google.com/g/rec.games.trading-cards.jyhad/c/9usl4idp-pY/m/LuT1iK1b4QIJ

**Comment by lionel-panhaleux** [comment]
It's already on all the cards requiring a Baron though.
