### ISSUE TITLE
Seeds of Corruption

### ISSUE THREAD

**Issue by codex-krcg** [lionel-panhaleux/krcg#724]
- **text:** Cannot be played by vampires who aren't controlled.
- **link:** https://groups.google.com/d/msg/rec.games.trading-cards.jyhad/80KRDjVFkyg/TBJso9Ra_9QJ

**Comment by GiottoVerducci** [comment]
Je ne comprends ni ce qui est écrit dans le champ texte, ni le rapport avec le lien.

**Comment by lionel-panhaleux** [comment]
Unrelated link, card is banned anyway.
