### ISSUE TITLE
Madness Network

### ISSUE THREAD

**Issue by codex-krcg** [lionel-panhaleux/krcg#729]
- **text:** If the impulse is passed to out-of-turn players and they all decline to act, the minion phase ends. The impulse to act is not passed back to the players whose turn it is.
- **link:** https://www.vekn.net/forum/rules-questions/73625-enkil-cog-madness-network-acting-outside-own-turn?start=6#73657

**Comment by SuakuOZ** [comment]
I'm not sure this requires a ruling update, since that just describes how the impulse works
With the explicit addition of impulse into the rulebook, this no longer requires a separate ruling

**Comment by lionel-panhaleux** [comment]
See #728

**Comment by lionel-panhaleux** [comment]
See #728
