### ISSUE TITLE
Hunger Moon

### ISSUE THREAD

**Issue by codex-krcg** [lionel-panhaleux/krcg#733]
- **text:** Rulung #1 does noit aply here. Hunger moon does not change the hunt value, and is not a repalcement effect. It moves from the vampire to the card AFTER it SUCCESFULY hunts. sicne the effect is depended on a succesful hunt, it cant make the hunt unsuncesful, unless it woudl state "instead", which it does not.
- **link:** https://groups.google.com/g/rec.games.trading-cards.jyhad/c/1vbIkgvKDJ0/m/3ErIIMXFgPIJ

**Comment by lionel-panhaleux** [comment]
You misunderstood the ruling. It does not mean Hunger Moon makes the hunt fail. It means if the hunt fails (the vampire does not gain blood), Hunger Moon's effect does not apply (he does not lose a blood to it). I'll reword it.
