### ISSUE TITLE
Form of Mist

### ISSUE THREAD

**Issue by codex-krcg** [lionel-panhaleux/krcg#739]
- **text:** If the combat continues or a new combat begins, the "action continues as if unblocked" effect is lost and the blood is not paid.  --- imo helpful clarification: during the new combat, sup Form of Mist can still be used to continue the action.
- **link:** https://groups.google.com/g/rec.games.trading-cards.jyhad/c/Puk_eXStfE8/m/jBRJ7bleXP4J

**Comment by SuakuOZ** [comment]
Could get a little tricky here
FoM cannot be played a second time at superior, so the only time this clarification is relevant is when superior FoM was NOT played on the first combat, but one the second one
This will require a fairly verbose statement to prevent ambiguity and I'm not sure that's a good thing here

**Comment by lionel-panhaleux** [comment]
Indeed it would be very misleading. Closing this one, I've added a sensible/similar ruling but on Psyche instead: see #734
