### ISSUE TITLE
byzar

### ISSUE THREAD

**Issue by warwar1980** [lionel-panhaleux/krcg#74]
idk,if i have beter example for byzar than link what you share,or is beter to both link be included for byzar rule : http://www.vekn.net/forum/rules-questions/19904-byzar-and-carlton-van-wyk?start=0

**Comment by warwar1980** [comment]
![image](https://user-images.githubusercontent.com/63711685/81235628-b5ed1c00-8ffb-11ea-87f0-ab16a9f81cd6.png)
him not going torpor,him stay in torpor and gain counter

**Comment by lionel-panhaleux** [comment]
Hm, I could have worded that better. If Amaranth is played, he would go to torpor. I can add propose:

"If a diablerie is attempted on him, he goes to (or stays in) torpor with an additional counter and the diablerie is unsuccessful."

Or I could reword it differently:

"His ability will make a diablerie unsuccessful (blood and equipment stay on him), although the diablerie action (if any) would still be considered successful."

What do you think ?

**Comment by warwar1980** [comment]
yea,3 is shorter,I also must say all 3 point are ok this time,you can chose any
