### ISSUE TITLE
Libertas

### ISSUE THREAD

**Issue by codex-krcg** [lionel-panhaleux/krcg#80]
- **text:** if you anarch with libertas declare block,but fail,oposing dont ned to pay extra blood
- **link:** https://groups.google.com/forum/#!msg/rec.games.trading-cards.jyhad/O5HUPRkKY-k/IVBZIwrEtboJ

**Comment by lionel-panhaleux** [comment]
I think this ruling is already included (same link in fact): 

> The additional cost does not apply once the minion has failed to block, so it does not apply to the cost of the action card. [LSJ 20080818]

Is the wording unclear ?
