### ISSUE TITLE
Resolution card Blood of Acid

### ISSUE THREAD

**Issue by warwar1980** [lionel-panhaleux/krcg#81]
explain is litle complicated,idk what is best to you usable. here is explain how Boa work agains frist strikehttp://www.vekn.net/forum/rules-questions/75755-resolution-card-blood-of-acid?start=0  . point with normal strike resolution is damage from BoA is not inflicted in same time and cannot be prevented in same window: http://www.vekn.net/forum/rules-questions/75755-resolution-card-blood-of-acid?start=6
maybe is good to mention how vag mystic cant be used,hmmm,i beleive coven too to prevent destructions http://www.vekn.net/forum/rules-questions/75755-resolution-card-blood-of-acid?start=6
Maybe is good to you read all,and you use what you think is best,is complicated ,yea,i agre

**Comment by warwar1980** [comment]
I see what you wrote about BoA,so you have some doubt. by rules whu i give you from ankha,one soak cant prevent strike and damage from BoA,you need 2 soak

**Comment by lionel-panhaleux** [comment]
That's not what I got from the thread - I read you can play prevention on BoA damage even if you haven't played one for strike damage. Didn't see anything about Soak.
You can play it to prevent strike, but if there are still damage prevention left why couldn't you use it on BoA ? Anyway I think you cannot, but I'd like to have a more clearcut and definitive ruling on this.

**Comment by warwar1980** [comment]
from ankha in link: http://www.vekn.net/forum/rules-questions/75755-resolution-card-blood-of-acid?start=6
![image](https://user-images.githubusercontent.com/63711685/82121046-8b812880-978a-11ea-91b8-9508850c1792.png)

from ankha too: 
![image](https://user-images.githubusercontent.com/63711685/82121086-cf742d80-978a-11ea-90f2-3870c9a90786.png)
on this: http://www.vekn.net/forum/rules-questions/75755-resolution-card-blood-of-acid?start=6

so by read all,you first prevent strike damage and other enwiromental(if have),window is close,now BoA inflict damage,you have new window for prevent,that I understand

**Comment by lionel-panhaleux** [comment]
Well, it is clear you prevent strike first then BoA. What is not clear is if you play Soak to prevent strike damage, can the *leftover* prevention of Soak be used for BoA or not ?

- On one hand for all cases prevention happens at the moment the card is played, it does not linger
- On the other hand BoA damage *is* done during strike resolution, it is not another strike or another round. The "window" we're talking about is neither in the rules, nor in Ankha answers.

Anyway, I opened a [new thread](http://www.vekn.net/forum/rules-questions/78629-damage-prevention-windows-what-can-you-soak#99817) to try and get a definitive answer on that. I'd tend to agree with you but I'd like to provide a clear ruling for the Codex.

I'll add it as soon as Ankha can confirm on the thread 😉

**Comment by warwar1980** [comment]
ankha answerd,so soak cant prevent strike and BoA

**Comment by lionel-panhaleux** [comment]
Added
