### ISSUE TITLE
Hatchling

### ISSUE THREAD

**Issue by codex-krcg** [lionel-panhaleux/krcg#95]
- **text:** This text is missing the fact that the Hatchling is non-unique. The official text is incorrect as well. When the card was reprinted in Heirs, they left out the non-unique part by mistake. Ben Peal even confirmed the error at attached link, but maybe Vincent just never saw the post. 
- **link:** http://www.vekn.net/forum/rules-questions/76597-are-hatchlings-non-unique

**Comment by lionel-panhaleux** [comment]
Sadly, a link with a post from a Rules Director is mandatory for ruling inclusion: this link is not compliant (even though I don't doubt for a second the Hatchling is non-unique).

**Comment by lionel-panhaleux** [comment]
I'll add a link to a Raw Recruit ruling instead - I think it's close enough. If someone finds a better link for Hatchling, let me know.
