### ISSUE TITLE
Misdirection

### ISSUE THREAD

**Issue by codex-krcg** [lionel-panhaleux/krcg#98]
- **text:** you can play and chose no lock and pay 0,did you know that? i dont,is here,but maybe is old rule 
- **link:** https://groups.google.com/forum/#!msg/rec.games.trading-cards.jyhad/0KEYzv22kjs/H4MWvI5F_hEJ

**Comment by lionel-panhaleux** [comment]
Yes it dates from before the card errata. Misdirection used to be `X Pool: lock X minions.`
