### ISSUE TITLE
Shalmath

### ISSUE THREAD

**Issue by codex-krcg** [lionel-panhaleux/krcg#99]
- **text:** Can Shalmath use his untap ability as he is stolen by Temptation-no
- **link:** http://www.vekn.net/forum/search?query=shalmath&searchdate=all&childforums=1&catids=6&start=15

**Comment by lionel-panhaleux** [comment]
So I put this one on Temptation. Is more of a ruling on Temptation (you cannot use Coven or Heidelberg either between the decision to use the counters and the control change). It has not much to do with Shalmath IMO.
